services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
      - ./results.json:/app/results.json
      - ./index.html:/app/index.html
    depends_on:
      - qdrant
    environment:
      - PYTHONUNBUFFERED=1
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - NODE_OPTIONS=--max-old-space-size=2048
    shm_size: "2gb"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
