services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
      - ./results.json:/app/results.json
      - ./index.html:/app/index.html
    environment:
      - PYTHONUNBUFFERED=1
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - NODE_OPTIONS=--max-old-space-size=2048
    shm_size: "2gb"
