services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8888:8080"
    command: >
      sh -c "SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml python3 -m searxng"
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
    restart: unless-stopped
