services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8888:8080"
    environment:
      SEARXNG_SETTINGS_PATH: /etc/searxng/custom_settings.yml
    command: python3 -m searxng
    volumes:
      - ./settings.yml:/etc/searxng/custom_settings.yml
    restart: unless-stopped
